# Generated by Django 4.0 on 2023-11-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kouka2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('category', models.CharField(choices=[('school', '学校関連行事'), ('festival', 'お祭り'), ('ivent', 'イベント'), ('cleaning', '清掃活動'), ('safety', '安心・安全'), ('others', 'その他')], max_length=50, verbose_name='カテゴリ')),
            ],
        ),
    ]
